### ISSUE TITLE
Serving assets in npm start

### ISSUE THREAD

**Issue by RemKolomna** [AngularClass/angular2-webpack-starter#232] opened 2016-01-18 08:24 UTC
I added to this starter image to /src/assets/img/test.png
After launching "npm start" the address
localhost:3000/assets/img/test.png is inaccessible, but address
localhost:3000/src/assets/img/test.png is working.

Which url should I set in image tag inside my html template?

**Comment by phil-lgr** [comment] 2016-01-18 15:10
+1, was fighting to get fonts being loaded from `url()` in my css.

**Comment by gdi2290** [comment] 2016-01-18 16:41
the assets folder should be copied over to `dist/assets` and serving `dist` for example we;re using `/assets/` for the icons https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/index.html#L13...L25

**Comment by RemKolomna** [comment] 2016-01-18 17:46
1)So I need to copy /src/assets/ to dist/assets manually each time I change smth in assets folder?
2)What do you mean by serving dist? Should I change server:dev command in package.json to serve dist folder instead of root folder? Will hot reload be working then?

**Comment by tmramo** [comment] 2016-01-19 12:48
Hi,

I am experiencing the same issue as RemKolomna.

Downloaded a (fresh) Webpack starter, installed it by running ‘npm install’ (with no issues at all). I started it with ‘npm start’ with Webpack reporting that the bundle is valid. When accessing localhost:3000, I cannot access the icons:

http://localhost:3000/assets/icon/favicon-16x16.png -> 404
http://localhost:3000/src/assets/icon/favicon-16x16.png -> 200

I am running Windows 10, with Node version 4.2.3 and npm version 2.14.7. I didn’t had any problems prior to copy-webpack-plugin and am thinking that it might be the cause of this issue.

**Comment by martinoppitz** [comment] 2016-01-20 12:23
Does anyone know why the whole src directory is accessible under dist?

**The CopyWebpackPlugin does nothing!**

**Comment by alvipeo** [comment] 2016-01-24 16:56
Actually, CopyWebpackPlugin works. According to setup it runs when you do 'npm run build:dev' but not when you 'npm start'. But the problem is there anyway - even if img file is copied to dist webserver returns 404. And this is really the big unknown for me...

**Comment by gdi2290** [comment] 2016-01-24 19:27
so the problem was that webpack-dev-server was serving `dist/` in-memory so if you added another file to `src/assets` you need to rebuild for it to copy over to `dist/` I changed the contentBase to use src so when you use `assets/` it's poining to `src/assets` rather than `dist/assets`. closed via https://github.com/AngularClass/angular2-webpack-starter/commit/c6f50c8af6c236903ab094674f595252dbb20bff

**Closed by gdi2290** 2016-01-24 19:27 UTC
Labels: bug
