### ISSUE TITLE
DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask polyfills.bundle.js:17086

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular2-webpack-starter#333] opened 2016-02-15 09:21 UTC
DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask polyfills.bundle.js:17086

 i see this message in Chrome console.

**Comment by samvloeberghs** [comment] 2016-02-15 11:07
It's a warning, don't care too much about it . Just don't use enqueueTask and you will be fine

**Comment by gdi2290** [comment] 2016-02-15 17:52
the problem is with angular2 so I'm sure they will fix it upstream eventually in a future beta release

**Comment by gdi2290** [comment] 2016-03-13 04:18
I'm going to close this issue since it's a problem with Angular 2 and will be updated in the near future

**Closed by gdi2290** 2016-03-13 04:18 UTC
Labels: [Angular 2] other module problems
