### ISSUE TITLE
e2e tests not run with PhantomJS

### ISSUE THREAD

**Issue by tamascsaba** [AngularClass/angular2-webpack-starter#55] opened 2015-08-19 08:33 UTC
Workflow:
```
npm run webdriver-start &
npm run express &
npm run e2e
```

Console only show, tests does not run
```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
```

I modifyed protractor.conf.js
```
exports.config = {
  baseUrl: 'http://localhost:8080/',
  capabilities: {
    'browserName': 'phantomjs',
    'phantomjs.binary.path': require('phantomjs').path,
    'phantomjs.ghostdriver.cli.args': ['--loglevel=INFO']
  },
  seleniumAddress: 'http://localhost:4444/wd/hub',
};

```

**Comment by gdi2290** [comment] 2015-08-24 04:44
is this needed after you made your PR? if it's still needed can you make another PR?

**Comment by dotcs** [comment] 2015-09-25 20:25
After https://github.com/angular-class/angular2-webpack-starter/pull/79 has been merged this issue should be fixed. For me `npm run e2e` runs without any problems now.

**Comment by gdi2290** [comment] 2015-09-25 20:29
awesome thanks!

**Comment by dotcs** [comment] 2015-09-25 21:14
Sorry @gdi2290, I think you have to reopen this. I have had Chrome in my setup, not phantomjs. The latter indeed makes problems. Unfortunately I have no quick solution, so we have to start over.

**Comment by tamascsaba** [comment] 2015-09-26 12:35
What promles makes PhantomJS Unit tests run?

**Comment by dotcs** [comment] 2015-10-22 08:34
Using the ["recommended" config](https://angular.github.io/protractor/#/browser-setup#setting-up-phantomjs) below, I could get the first E2E test to work (which checks the title of the page), but the following tests fail because it seems that PhantomJS does not wait for Angular before running the tests which is why they fail with an `InvalidElementStateError` [1].

```
capabilities: {
    'browserName': 'phantomjs',

    /*
     * Can be used to specify the phantomjs binary path.
     * This can generally be ommitted if you installed phantomjs globally.
     */
    'phantomjs.binary.path': require('phantomjs').path,

    /*
     * Command line args to pass to ghostdriver, phantomjs's browser driver.
     * See https://github.com/detro/ghostdriver#faq
     */
    'phantomjs.ghostdriver.cli.args': ['--loglevel=DEBUG']
  },
```
The linked document absolve also states:
> Note: We recommend against using PhantomJS for tests with Protractor. There are many reported issues with PhantomJS crashing and behaving differently from real browsers.

So perhaps we should not use PhantomJS at all for E2E tests. 


[1]: Some details on the `InvalidElementStateError`: 

```
InvalidElementStateError: {"errorMessage":"SYNTAX_ERR: DOM Exception 12","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"59","Content-Type":"application/json; charset=utf-8","Host":"localhost:20091","User-Agent":"Apache-HttpClient/4.4.1 (Java/1.8.0_66)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"css selector\",\"value\":\"* /deep/ app /deep/ main\"}","url":"/elements","urlParsed":{"anchor":"","query":"","file":"elements","directory":"/","path":"/elements","relative":"/elements","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/elements","queryKey":{},"chunks":["elements"]},"urlOriginal":"/session/87a8c3c0-7896-11e5-8b2b-f10d392379d5/elements"}}
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
```

**Comment by gdi2290** [comment] 2015-11-06 03:03
If the issue is still valid please open a PR

**Closed by gdi2290** 2015-11-06 03:03 UTC
Labels: bug, help wanted
