### ISSUE TITLE
Can't start the project (fresh installation)

### ISSUE THREAD

**Issue by jakub2** [AngularClass/angular2-webpack-starter#1111] opened 2016-10-18 08:28 UTC
* **I'm submitting a ...**
[x] bug report

* **What is the current behavior?**
I just cloned the repo and installed it. Then it failed to start. Below is my debug log.

* **What is the expected behavior?**
It should start the project.

* **Please tell us about your environment:**

I'm behind a proxy (corporate environment). Do I need to set that up somewhere?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\software\\nodejs\\node.exe',
1 verbose cli   'C:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'server:dev:hmr' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 verbose run-script [ 'preserver:dev:hmr', 'server:dev:hmr', 'postserver:dev:hmr' ]
5 info lifecycle angular2-webpack-starter@5.0.5~preserver:dev:hmr: angular2-webpack-starter@5.0.5
6 silly lifecycle angular2-webpack-starter@5.0.5~preserver:dev:hmr: no script for preserver:dev:hmr, continuing
7 info lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: angular2-webpack-starter@5.0.5
8 verbose lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: PATH: C:\software\nodejs\node_modules\npm\bin\node-gyp-bin;c:\web\db-002\node_modules\.bin;C:\software\cmder\bin;C:\software\cmder\vendor\git-for-windows\cmd;C:\software\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\software\cmder\vendor\conemu-maximus5;C:\software\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Citrix\System32\;C:\Program Files\Citrix\ICAService\;C:\Program Files\AppSense\Application Manager\Agent\Plugins\EcaRulesEngine\;C:\software\nodejs\;C:\Users\ny563\AppData\Local\atom\bin;C:\software\Ruby23-x64\bin;C:\Users\ny563\AppData\Roaming\npm;C:\software\cmder\vendor\git-for-windows\usr\bin;C:\software\cmder\vendor\git-for-windows\usr\share\vim\vim74;C:\software\cmder\
10 verbose lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: CWD: c:\web\db-002
11 silly lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: Args: [ '/d /s /c', 'npm run server:dev -- --inline --hot' ]
12 silly lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.0.5~server:dev:hmr: Failed to exec server:dev:hmr script
14 verbose stack Error: angular2-webpack-starter@5.0.5 server:dev:hmr: `npm run server:dev -- --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\software\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\software\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-webpack-starter@5.0.5
16 verbose cwd c:\web\db-002
17 error Windows_NT 6.1.7601
18 error argv "C:\\software\\nodejs\\node.exe" "C:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev:hmr"
19 error node v6.8.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.0.5 server:dev:hmr: `npm run server:dev -- --inline --hot`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.0.5 server:dev:hmr script 'npm run server:dev -- --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev -- --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jakub2** [comment] 2016-10-18 08:49
Ok, so during installation I get this error - any ideas what to do please?

> execSync@1.0.2 install c:\web\db-002\node_modules\execSync > node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ Error: spawn node-gyp ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

**Comment by d3viant0ne** [comment] 2016-10-18 23:14
@jakub2 - This looks to be some sort of funky Node/Windows problem. The very first thing I would try would be installing the current Node LTS version instead of node 6.8.x and see how it goes.

**Comment by jakub2** [comment] 2016-10-19 09:07
That didn't help. Still the same problem. I'm on a Windows virtual machine. Any ideas?

**Comment by adstep** [comment] 2016-10-19 19:06
I'm also hitting this issue running windows.

**Comment by d3viant0ne** [comment] 2016-10-20 10:50
@jakub2 @adstep - I'll have to spin up a Windows VM at take a look at it. I'll see if I can get to it this evening after work.

**Comment by jakub2** [comment] 2016-10-20 11:09
Awesome, let me know how it goes.


Jakub Mandrysz
jakub@margin.cz

<http://t.sidekickopen17.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2BpBgTN65jFx6QsyWYW3LjdLH56dPsPf2WjYQK02?t=http%3A%2F%2Fmargin.cz%2F&si=6259757128089600&pi=b3775cb6-881f-4ab6-b71e-97a6c9a6d0a8>

**Comment by gdi2290** [comment] 2016-10-24 02:46
yo @d3viant0ne any update on this?

**Comment by d3viant0ne** [comment] 2016-10-24 07:39
@gdi2290 - The issue @jakub2 & @adstep are seeing is valid. I'm working on the `why` now. Should have this problem run down in an hour.

**Comment by d3viant0ne** [comment] 2016-10-27 01:33
Closing this for now as the issue is not present in #master

If either of you are still having issues on windows, contact me directly & I will see if I can get you squared away.

**Closed by d3viant0ne** 2016-10-27 01:33 UTC
Labels: question
