### ISSUE TITLE
No material2 branch on github repo

### ISSUE THREAD

**Issue by utilitydelta** [AngularClass/angular2-webpack-starter#1442] opened 2017-01-30 05:04 UTC
Hi,

The readme says there is a material2 branch that we can clone to grab the starter with material2. It doesn't seem to exist however. Any idea where it went?

Thanks!
Tyson

**Comment by seiyria** [comment] 2017-02-01 00:12
duplicate of https://github.com/AngularClass/angular2-webpack-starter/issues/1414

**Closed** 2017-02-01 06:31 UTC
