### ISSUE TITLE
npm run e2e   error

### ISSUE THREAD

**Issue by felix307253927** [AngularClass/angular2-webpack-starter#463] opened 2016-03-23 10:12 UTC
npm run e2e error:

node_modules/zone.js/lib/browser/property-descriptor.ts (73,19): Cannot find name 'Zone'. (2304)
node_modules/zone.js/lib/browser/register-element.ts (24,32): Cannot find name 'Zone'. (2304)
node_modules/zone.js/lib/browser/register-element.ts (27,40): Cannot find name 'Zone'. (2304)
node_modules/zone.js/lib/browser/register-element.ts (30,38): Cannot find name 'Zone'. (2304)

**Comment by StormToft** [comment] 2016-03-23 17:01
@felix307253927 could this be a duplicate of #452 ?

**Comment by felix307253927** [comment] 2016-03-24 01:52
@StormToft  i run it in Linux

**Comment by spawnius** [comment] 2016-04-16 21:50
I ran e2e tests on windows and linux now without issues , can this be closed?

**Closed** 2016-04-16 21:53 UTC
