### ISSUE TITLE
templateUrl 404 error loading app.html using webPack server

### ISSUE THREAD

**Issue by gaurav2887** [AngularClass/angular2-webpack-starter#1494] opened 2017-02-07 22:21 UTC
I am getting 404 error  while using `templateUrl: './app.html'` when running app locally on Webpack server. Code works fine with `template:require('./app.html')` syntax.

Any suggestion how can i make it work with templateUrl?

**Comment by shlomiassaf** [comment] 2017-02-07 23:05
duplicate of #1484

**Closed by shlomiassaf** 2017-02-07 23:05 UTC
