### ISSUE TITLE
npm run test - Could not find source map for ...

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#1188] opened 2016-11-20 10:03 UTC
Can someone please fix these errors? Lots of them when 'npm run test'. I tried to google it but no luck, I don't know how to fix it.

**Comment by gdi2290** [comment] 2016-11-20 21:19
I would need some help to fix this
cc @d3viant0ne @katallaxie

**Comment by adonespitogo** [comment] 2016-11-21 08:04
Putting my comment here for notifications..

**Comment by centigrade-thomas-becker** [comment] 2016-11-21 13:45
After downloading and installing I get the following output when running `npm test`

```

> angular2-webpack-starter@1.0.0 test c:\webpack
> karma start


START:

webpack: bundle is now VALID.
webpack: bundle is now INVALID.

webpack: bundle is now VALID.
21 11 2016 14:43:15.153:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
21 11 2016 14:43:15.158:INFO [launcher]: Launching browser Chrome with unlimited concurrency
21 11 2016 14:43:15.189:INFO [launcher]: Starting browser Chrome
21 11 2016 14:43:18.529:INFO [Chrome 53.0.2785 (Windows 8.1 0.0.0)]: Connected on socket /#PrOgr-gkmkCsKt_9AAAA with id 67048421
  About
    √ should log ngOnInit
  App
    √ should have a url
  Home
    √ should have default data
    √ should have a title
    √ should log ngOnInit
  Title
    √ should have http
    √ should get data from the server
  x-large directive
    √ should sent font-size to x-large

Finished in 0.454 secs / 0.402 secs

SUMMARY:
√ 8 tests completed
Error: Could not find source map for: "c:\webpack\src\app\about\about.component.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
Error: Could not find source map for: "c:\webpack\src\app\app.component.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
Error: Could not find source map for: "c:\webpack\src\app\app.service.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
Error: Could not find source map for: "c:\webpack\src\app\home\home.component.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
Error: Could not find source map for: "c:\webpack\src\app\home\title\index.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
Error: Could not find source map for: "c:\webpack\src\app\home\title\title.service.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
Error: Could not find source map for: "c:\webpack\src\app\home\x-large\x-large.directive.ts"
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:257:11
    at Array.forEach (native)
    at c:\webpack\node_modules\remap-istanbul\lib\remap.js:214:22
    at Array.forEach (native)
    at remap (c:\webpack\node_modules\remap-istanbul\lib\remap.js:213:12)
    at RemapCoverageReporter.onCoverageComplete (c:\webpack\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (c:\webpack\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (c:\webpack\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (c:\webpack\node_modules\karma-coverage\lib\reporter.js:68:16)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (c:\webpack\node_modules\karma\lib\browser_collection.js:93:21)
    at c:\webpack\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)

=============================== Coverage summary ===============================
Statements   : 84.52% ( 71/84 )
Branches     : 74.36% ( 29/39 )
Functions    : 66.67% ( 18/27 )
Lines        : 84.15% ( 69/82 )
================================================================================
```

**Comment by M1strall** [comment] 2016-11-21 16:01
Same here, coverage report itself/remap works though.

**Comment by rgeraldporter** [comment] 2016-11-21 19:27
Also seeing this.

**Comment by BrianRT** [comment] 2016-11-21 20:11
So is remap-istanbul being fed incorrect values?  It's not returning any "matches" in the `remap` function in `remap.js`.  

Starting at line 259:
```
if (!match && !rawSourceMap) {
	/* We couldn't find a source map, so will copy coverage after warning. */
	warn(new Error('Could not find source map for: "' + filePath + '"'));
	try {
		fileCoverage.code = String(fs.readFileSync(filePath)).split('\n');
	}
	catch (error) {
		warn(new Error('Could find source for : "' + filePath + '"'));
	}
        srcCoverage[filePath] = fileCoverage;
	return;
}
```

I'm seeing that `match` is "null" and `rawSourceMap` is "undefined".

**Comment by d3viant0ne** [comment] 2016-11-21 21:41
@gdi2290 - I'll see to this after work

**Comment by d3viant0ne** [comment] 2016-11-22 19:51
As a temporary work around, lock `istanbul-instrumenter-loader` to `0.2.0` until I can get a fix for this landed in master.

//cc @Nocomm  @rgeraldporter @M1strall @centigrade-thomas-becker @adonespitogo @alvipeo

**Comment by gdi2290** [comment] 2016-11-22 20:32
@d3viant0ne thanks for looking into it

**Comment by centigrade-thomas-becker** [comment] 2016-11-24 07:30
Thanks for the heads up, but fixing the version to `0.2.0` does not work for me.

**Comment by d3viant0ne** [comment] 2016-11-24 07:38
@centigrade-thomas-becker - I've evidently deviated too far from the starter where that change was effective. Working this issue again against current master.

**Comment by nqcuong72** [comment] 2016-11-24 07:39
I am the same problem with version 0.2.0. It does not work

**Comment by jeffvictorino** [comment] 2016-11-24 09:41
Subscribed to this, version 0.2.0 doesn't work.

Would really love to use this starter for the code coverage.

**Comment by rhday74** [comment] 2016-11-24 22:41
I ran into this same issue myself.  currently locked at 0.2.0 on istanbul-instrumenter-loader with code coverage working however.  v1.0.0 hoses it for sure

**Comment by d3viant0ne** [comment] 2016-11-25 02:48
Last good config - ee9aafbea15aa9893e615f7133435fbcf9481b77 ( if you disable tslint in webpack.test.js )

Broken here - https://github.com/AngularClass/angular2-webpack-starter/commit/efe9748ee7e1f931318c649ae28b9a0a2d78644b

Requires version locking `istanbul-instrumenter-loader` to 0.2.0

> Working through the changes in the webpack configs that broke the sourcemaps now.

**Comment by d3viant0ne** [comment] 2016-11-25 03:02
![screen shot 2016-11-24 at 9 02 22 pm](https://cloud.githubusercontent.com/assets/8420490/20613418/525e07ce-b289-11e6-913b-2aae001ec705.png)

**To get this working on master:**

- Version lock `istanbul-instrumenter-loader` to 0.2.0
- In the `module`  rules collection change `use:` to `loader:`

**Closed** 2016-11-25 04:24 UTC
Labels: bug, help wanted

**Comment by PhillipBerger-BSFT** [comment] 2016-12-02 18:04
This is still broken when:

> Version lock istanbul-instrumenter-loader to 0.2.0
In the module rules collection of the webpack.test.js change use: to loader:

**Comment by d3viant0ne** [comment] 2016-12-02 21:18
No, it isn't - https://travis-ci.org/AngularClass/angular2-webpack-starter/jobs/180712444

**Comment by shlomiassaf** [comment] 2016-12-11 12:45
FYI,

For tracking when we can upgrade:

The fix for this has landed, it required a fix in 2 packages.
  - [istanbul-instrumenter-loader](https://github.com/deepsweet/istanbul-instrumenter-loader/issues/35)
  - [remap-istanbul](https://github.com/SitePen/remap-istanbul/pull/87)

So, basically the up-to-date version of **istanbul-instrumenter-loader** is fine.
The problem is with **remap-istanbu**, we need to wait for them to publish *0.8* that will include the fix.

I disabled the reports since it's a lot of work for me to go back from **use** to **loaders**

**Comment by shlomiassaf** [comment] 2016-12-11 12:46
@d3viant0ne I would **reopen** this ticket since the problem is not solved, it's just a workaround.

It a good reminder for upgrading when possible.

You're call.

**Comment by b-tiwari** [comment] 2017-06-09 18:34
was this ever fixed? I am getting the same error, I have the latest version of `karma-remap-coverage` and tried with 0.2.0 of `istanbul-instrumenter-loader` as well its latest.

**Comment by thetric** [comment] 2017-06-09 19:45
@b-tiwari I use `karma-coverage-istanbul-reporter` with `istanbul-instrumenter-loader` to generate code coverage reports. You just need to add this to your karma.conf.js:

```js
       reporters: ['coverage-istanbul'], 

        coverageIstanbulReporter: {
            reports: ['text-summary', 'html'],
            fixWebpackSourcePaths: true,
        },
```

**Comment by b-tiwari** [comment] 2017-06-09 20:55
I noticed it was creating ts sourcemaps for first few files and then throwing `Error: Could not find source map for..` error for remaining files. So in tsconfig.json compilerOptions, I tried `inlineSourceMap: true` instead of individual map files with `sourceMap: true` and  it worked!
