### ISSUE TITLE
Error on npm run build:dev

### ISSUE THREAD

**Issue by cpiock** [AngularClass/angular2-webpack-starter#1372] opened 2017-01-13 17:02 UTC
Just tried to clone the acutal starterkit and run npm run build:dev after npm install. It fails with this and ideas?

```
 var content = Buffer.from(JSON.stringify(manifest, null, 2), "utf8");
                        ^
TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at LibManifestPlugin.<anonymous> (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\LibManifestPlugin.js:46:25)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (C:\temp\angular2-webpack-starter\node_modules\webpack\node_modules\async\dist\async.js:941:9)
    at eachOf (C:\temp\angular2-webpack-starter\node_modules\webpack\node_modules\async\dist\async.js:991:5)
    at Object.eachLimit (C:\temp\angular2-webpack-starter\node_modules\webpack\node_modules\async\dist\async.js:3089:3)
    at LibManifestPlugin.<anonymous> (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\LibManifestPlugin.js:14:9)
    at Compiler.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:142:13)
    at Compiler.emitAssets (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compiler.js:292:7)
    at onCompiled (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compiler.js:231:11)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compiler.js:477:13
    at next (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:138:11)
    at Compiler.<anonymous> (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:142:13)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compiler.js:474:10
    at Compilation.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:131:46)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:615:19
    at Compilation.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:131:46)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:606:11
    at Compilation.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:131:46)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:601:10
    at Compilation.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:131:46)
    at sealPart2 (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:597:9)
    at Compilation.applyPluginsAsyncSeries (C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:131:46)
    at Compilation.seal (C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:545:8)
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compiler.js:471:16
    at C:\temp\angular2-webpack-starter\node_modules\tapable\lib\Tapable.js:225:11
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:452:11
    at C:\temp\angular2-webpack-starter\node_modules\webpack\lib\Compilation.js:423:13

```

**Comment by d3viant0ne** [comment] 2017-01-13 17:41
What OS & Node Version?

`build:dev` on a fresh clone ...

![screen shot 2017-01-13 at 11 40 28 am](https://cloud.githubusercontent.com/assets/8420490/21939369/1e7907ec-d985-11e6-9baa-1a1957d3c75a.png)

**Comment by cpiock** [comment] 2017-01-13 18:35
node v4.4.7
npm  v3.10.5
Window 10 64bit

**Comment by d3viant0ne** [comment] 2017-01-13 18:51
So a windows problem or more likely a node 4 problem. Given we are about to drop support for node 4.x as it's no longer the LTS version, my suggestion would be to get on the current LTS version of NodeJS and see if that resolves the issue.

**Comment by cpiock** [comment] 2017-01-13 19:51
ok updating to node 694 LTS and removing node_modules and reinstall it solves this problem but now i have this errors.
```
ERROR in [at-loader] Cannot find type definition file for 'hammerjs'.
ERROR in [at-loader] Cannot find type definition file for 'node'.
ERROR in [at-loader] src\app\app.component.ts:19:5
    Cannot find name 'require'ERROR in [at-loader] Cannot find type definition file for 'hammerjs'.
ERROR in [at-loader] Cannot find type definition file for 'node'.
ERROR in [at-loader] src\app\app.component.ts:19:5
    Cannot find name 'require'
```

**Comment by scallacs** [comment] 2017-01-13 21:16
I've got the same error as @cpiock... 
```
ERROR in [at-loader] Cannot find type definition file for 'hammerjs'.
ERROR in [at-loader] Cannot find type definition file for 'node'.
```
node: v6.6.0
npm: 4.1.1
Window 10 64bit

What I've did: 

```
git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git 
cd angular2-webpack-starter
npm install
npm run build:dev
```

Error: 
```
F:\Dev\tests\angular2-webpack-starter [master ≡]> npm run build:dev

> angular2-webpack-starter@5.4.1 build:dev F:\Dev\tests\angular2-webpack-starter
> npm run clean:dist && webpack --config config/webpack.dev.js --progress --profile


> angular2-webpack-starter@5.4.1 clean:dist F:\Dev\tests\angular2-webpack-starter
> npm run rimraf -- dist


> angular2-webpack-starter@5.4.1 rimraf F:\Dev\tests\angular2-webpack-starter
> rimraf "dist"

DLL: Checking if DLLs are valid.
DLL: Rebuilding...
DLL: Bundling done, all DLLs are valid.
 10% building modules 0/2 modules 2 active ...2-webpack-starter\src\main.browser.ts
[at-loader] Using typescript@2.1.5 from typescript and "tsconfig.json" from F:\Dev\tests\angular2-webpack-starter\tsconfig.webpack.json.
                 32% building modules 189/194 modules 5 active ...pp\no-content\no-content.component.ts================================== ng-router-loader ==================================
Importer:    F:\Dev\tests\angular2-webpack-starter\src\app\app.routes.ts
Raw Request: loadChildren: './+detail#DetailModule'
Replacement: loadChildren: () => System.import('F:\\Dev\\tests\\angular2-webpack-starter\\src\\app\\+detail\\index')  .then( (module: any) => module['DetailModule'] )
======================================================================================
================================== ng-router-loader ==================================
Importer:    F:\Dev\tests\angular2-webpack-starter\src\app\app.routes.ts
Raw Request: loadChildren: './+barrel#BarrelModule'
Replacement: loadChildren: () => System.import('F:\\Dev\\tests\\angular2-webpack-starter\\src\\app\\+barrel\\index')  .then( (module: any) => module['BarrelModule'] )
============ 35% building modules 216/219 modules 3 active ...r\src\assets\mock-data\mock-data.json================================== ng-router-loader ==================================
Importer:    F:\Dev\tests\angular2-webpack-starter\src\app\+detail\detail.routes.ts
Raw Request: loadChildren: './+child-detail#ChildDetailModule'
Replacement: loadChildren: () => System.import('F:\\Dev\\tests\\angular2-webpack-starter\\src\\app\\+detail\\+child-detail\\index')  .then( (module: any) => module['ChildDetailModule'] )
============ 36% building modules 218/220 modules 2 active ...rc\app\+detail\+child-detail\index.ts================================== ng-router-loader ==================================
Importer:    F:\Dev\tests\angular2-webpack-starter\src\app\+barrel\barrel.routes.ts
Raw Request: loadChildren: './+child-barrel#ChildBarrelModule'
Replacement: loadChildren: () => System.import('F:\\Dev\\tests\\angular2-webpack-starter\\src\\app\\+barrel\\+child-barrel\\index')  .then( (module: any) => module['ChildBarrelModule'] )
============14272ms building modules
0ms sealing
0ms optimizing
16ms basic module optimization
0ms module optimization
0ms advanced module optimization
16ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
0ms module and chunk tree optimization
0ms module reviving
0ms module order optimization
17ms module id optimization
4ms chunk reviving
0ms chunk order optimization
0ms chunk id optimization
0ms hashing
0ms module assets processing
31ms chunk assets processing
16ms additional chunk assets processing
0ms recording
16ms additional asset processing
34ms chunk asset optimization
 94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 6 errors                                 535ms asset optimization
47ms emitting
Hash: 00b09aa81366e78c02a9
Version: webpack 2.2.0-rc.4
Time: 22139ms
                                 Asset       Size  Chunks                    Chunk Names
      assets/icon/apple-icon-72x72.png    4.23 kB          [emitted]
                            0.chunk.js    4.19 kB       0  [emitted]
                            2.chunk.js  170 bytes       2  [emitted]
                        main.bundle.js    41.7 kB       3  [emitted]         main
                            4.chunk.js    3.83 kB       4  [emitted]
                            5.chunk.js    3.83 kB       5  [emitted]
                   polyfills.bundle.js    37.4 kB       6  [emitted]         polyfills
                        0.chunk.js.map     3.6 kB       0  [emitted]
                        1.chunk.js.map     3.6 kB       1  [emitted]
                        2.chunk.js.map  363 bytes       2  [emitted]
                    main.bundle.js.map    43.4 kB       3  [emitted]         main
                        4.chunk.js.map    3.09 kB       4  [emitted]
                        5.chunk.js.map    3.09 kB       5  [emitted]
               polyfills.bundle.js.map    73.1 kB       6  [emitted]         polyfills
                     assets/humans.txt  268 bytes          [emitted]
                   assets/css/.gitkeep   15 bytes          [emitted]
  assets/icon/android-icon-192x192.png    9.71 kB          [emitted]
  assets/icon/android-icon-144x144.png    8.43 kB          [emitted]
    assets/icon/android-icon-36x36.png     2.3 kB          [emitted]
    assets/icon/android-icon-48x48.png    2.92 kB          [emitted]
    assets/icon/android-icon-72x72.png    4.23 kB          [emitted]
    assets/icon/android-icon-96x96.png     5.6 kB          [emitted]
    assets/icon/apple-icon-120x120.png    6.92 kB          [emitted]
    assets/icon/apple-icon-144x144.png    8.43 kB          [emitted]
    assets/icon/apple-icon-114x114.png    6.55 kB          [emitted]
    assets/icon/apple-icon-152x152.png    8.99 kB          [emitted]
    assets/icon/apple-icon-180x180.png      11 kB          [emitted]
      assets/icon/apple-icon-60x60.png    3.56 kB          [emitted]
                            1.chunk.js    4.19 kB       1  [emitted]
      assets/icon/apple-icon-57x57.png     3.4 kB          [emitted]
      assets/icon/apple-icon-76x76.png    4.46 kB          [emitted]
assets/icon/apple-icon-precomposed.png    10.3 kB          [emitted]
         assets/icon/favicon-16x16.png    1.52 kB          [emitted]
            assets/icon/apple-icon.png    10.3 kB          [emitted]
         assets/icon/browserconfig.xml  282 bytes          [emitted]
                      assets/data.json   33 bytes          [emitted]
         assets/icon/favicon-32x32.png    2.07 kB          [emitted]
               assets/icon/favicon.ico    1.15 kB          [emitted]
         assets/icon/favicon-96x96.png     5.6 kB          [emitted]
       assets/icon/ms-icon-144x144.png    8.43 kB          [emitted]
       assets/icon/ms-icon-150x150.png    8.88 kB          [emitted]
         assets/icon/ms-icon-70x70.png    4.12 kB          [emitted]
       assets/icon/ms-icon-310x310.png    24.1 kB          [emitted]
           assets/img/angular-logo.png      19 kB          [emitted]
    assets/img/angularclass-avatar.png    32.8 kB          [emitted]
      assets/img/angularclass-logo.png    36.7 kB          [emitted]
                     assets/robots.txt   34 bytes          [emitted]
       assets/mock-data/mock-data.json   25 bytes          [emitted]
                  assets/manifest.json  689 bytes          [emitted]
              assets/service-worker.js   45 bytes          [emitted]
                            robots.txt   34 bytes          [emitted]
                            humans.txt  268 bytes          [emitted]
                         vendor.dll.js    3.88 MB          [emitted]  [big]
                     vendor.dll.js.map    3.92 MB          [emitted]
                      polyfills.dll.js     332 kB          [emitted]  [big]
                  polyfills.dll.js.map     412 kB          [emitted]
                            index.html    2.71 kB          [emitted]
   [9] ./src/app/environment.ts 1.13 kB {3} [built]
       [] -> factory:0ms building:62ms = 62ms
  [10] delegated ./node_modules/@angularclass/hmr/dist/index.js from dll-reference vendor_lib 42 bytes {3} [not cacheable] [built]
       [] -> factory:100ms building:0ms dependencies:0ms = 100ms
  [24] ./src/app/index.ts 39 bytes {3} [built]
       [] -> factory:15ms building:85ms = 100ms
  [25] ./~/core-js/es6/array.js 944 bytes {6} [built]
       [] -> factory:147ms building:69ms dependencies:432ms = 648ms
  [26] ./~/core-js/es6/date.js 231 bytes {6} [built]
       [] -> factory:147ms building:69ms = 216ms
  [27] ./~/core-js/es6/function.js 185 bytes {6} [built]
       [] -> factory:147ms building:54ms dependencies:447ms = 648ms
  [28] ./~/core-js/es6/map.js 207 bytes {6} [built]
       [] -> factory:147ms building:69ms dependencies:501ms = 717ms
  [29] ./~/core-js/es6/math.js 690 bytes {6} [built]
       [] -> factory:147ms building:54ms dependencies:447ms = 648ms
  [30] ./~/core-js/es6/number.js 602 bytes {6} [built]
       [] -> factory:147ms building:54ms dependencies:447ms = 648ms
  [31] ./~/core-js/es6/object.js 881 bytes {6} [built]
       [] -> factory:147ms building:85ms dependencies:416ms = 648ms
  [32] ./~/core-js/es6/parse-float.js 95 bytes {6} [built]
       [] -> factory:147ms building:54ms dependencies:447ms = 648ms
  [33] ./~/core-js/es6/parse-int.js 91 bytes {6} [built]
       [] -> factory:147ms building:54ms dependencies:447ms = 648ms
  [46] delegated ./node_modules/zone.js/dist/zone.js from dll-reference polyfills_lib 42 bytes {6} [not cacheable] [built]
       [] -> factory:169ms building:0ms = 169ms
 [207] ./src/main.browser.ts 1.73 kB {3} [built]
        factory:163ms building:5559ms = 5722ms
 [208] ./src/polyfills.browser.ts 1.17 kB {6} [built]
        factory:63ms building:5590ms = 5653ms
    + 212 hidden modules

ERROR in [at-loader] Cannot find type definition file for 'hammerjs'.

ERROR in [at-loader] Cannot find type definition file for 'node'.

ERROR in [at-loader] src\app\app.component.ts:19:5
    Cannot find name 'require'.

ERROR in [at-loader] src\app\home\home.component.ts:20:13
    Cannot find name 'require'.

ERROR in [at-loader] src\app\home\home.component.ts:22:13
    Cannot find name 'require'.

ERROR in [at-loader] src\polyfills.browser.ts:44:3
    Cannot find name 'require'.
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
           [] -> factory:100ms building:363ms = 463ms
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
           [] -> factory:369ms building:1206ms = 1575ms
       [2] (webpack)/buildin/module.js 567 bytes {0} [built]
           [] -> factory:369ms building:1206ms = 1575ms
       [3] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 2.09 kB {0} [built]
            factory:163ms building:5559ms = 5722ms

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Stephane\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
npm ERR! node v6.6.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.4.1 build:dev: `npm run clean:dist && webpack --config config/webpack.dev.js --progress --profile`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.4.1 build:dev script 'npm run clean:dist && webpack --config config/webpack.dev.js --progress --profile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && webpack --config config/webpack.dev.js --progress --profile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Dev\tests\angular2-webpack-starter\npm-debug.log
```

**Comment by cheshirec7** [comment] 2017-01-13 22:36
Cloned this project and it works in the browser but I get these errors:

[at-loader] Checking finished with 6 errors
[at-loader] Cannot find type definition file for 'hammerjs'.
[at-loader] Cannot find type definition file for 'node'.
[at-loader] src\app\app.component.ts:19:5
    Cannot find name 'require'.
[at-loader] src\app\home\home.component.ts:20:13
    Cannot find name 'require'.
[at-loader] src\app\home\home.component.ts:22:13
    Cannot find name 'require'.
[at-loader] src\polyfills.browser.ts:44:3
    Cannot find name 'require'.

Win10/64
node: 7.4.0

When I revert back to typescript 2.0.10, no errors.

**Comment by gcphost** [comment] 2017-01-14 01:56
Same thing on MacOS with node v5.9.1

**Comment by gcphost** [comment] 2017-01-14 02:06
Changed to webpack 2.2.0-rc.3 and built without error.

**Comment by colinskow** [comment] 2017-01-14 04:45
Since this is now a duplicate of #1371 I'm closing to keep the conversation there.

**Closed by colinskow** 2017-01-14 04:45 UTC
Labels: bug, [Windows] windows OS problems
