### ISSUE TITLE
Problems with newest source

### ISSUE THREAD

**Issue by trsh** [AngularClass/angular2-webpack-starter#1251] opened 2016-12-08 11:59 UTC
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

On npm start I get errors 

![err](https://cloud.githubusercontent.com/assets/3727523/21009238/375bc9b4-bd4e-11e6-85ba-4e27ffadee78.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

Get latest source, npm install. npm start

* **What is the expected behavior?**

No errors

* **Please tell us about your environment:**

- Angular version: 2.2.1
- Browser: all

**Comment by bonaventoora** [comment] 2016-12-08 12:15
double of #1249

**Comment by trsh** [comment] 2016-12-08 12:38
@bonaventoora lol, I was an hour late

**Comment by d3viant0ne** [comment] 2016-12-08 15:22
Closing - Duplicate of #1249 for which the workaround has already been merged into master.

**Closed by d3viant0ne** 2016-12-08 15:22 UTC
