### ISSUE TITLE
problem with typings install on win7 

### ISSUE THREAD

**Issue by maku** [AngularClass/angular2-webpack-starter#191] opened 2016-01-04 07:46 UTC
I did a fresh clone and than I have a problem with typings:
When I execute "typings install" I get the following error:

```typings ERR! message Missing dependency "es6-promise", unable to compile dependency tree```

I am on Win7 Prof with node v.4.2.4 and npm 2.14.12

**Comment by blakeembrey** [comment] 2016-01-05 20:05
Thanks for the report, I'll look into improving this error messaging from within Typings and we can go from there.

**Comment by blakeembrey** [comment] 2016-01-06 04:05
@maku I just published `0.5.0` of `typings` and it'll contain better error messages when a dependency fails to resolve. Would you mind updating and giving it a go?

**Comment by maku** [comment] 2016-01-06 11:28
@blakeembrey I will give it a try. But I can only do it at next monday.

**Comment by maku** [comment] 2016-01-11 06:47
@blakeembrey With the latest angular2-webpack-starter version (after a fresh clone) the reported error is the same ```typings ERR! message Missing dependency "es6-promise", unable to compile dependency tree```

**Comment by dannmartens** [comment] 2016-01-11 15:35
I'm seeing a different error, which looks like an issue with 'typings' itself.

It seems to be caused by a proxy which intercepts the SSL certificate. Typings supports a proxy config as of late, should it have strict-ssl, as well?


> typings install

typings ERR! message Unable to resolve "github:typings/typed-es6-promise#9243c53f70fb4909ed7cce3094bec221b9fb6d5f"

typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/typings/typed-es6-promise/9243c53f70fb4909ed7cce3094bec221b9fb6d5f/typings.json"

typings ERR! caused by unable to get local issuer certificate

**Comment by blakeembrey** [comment] 2016-01-11 17:40
@maku Can you please try with the latest typings version - the error message should be clearer.

@dannmartens Feel free to open an issue on `typings`.

**Comment by maku** [comment] 2016-01-12 06:41
@blakeembrey After updating typings (current version is 0.6.1) I get the following:
```
typings ERR! message Unable to resolve "github:typings/typed-es6-promise#9243c53f70fb4909ed7cce3094bec221b9fb6d5f"
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/typings/typed-es6-promise/9243c53f70fb4909ed7cce3094bec221b9fb6d5f/typings.json"
typings ERR! caused by getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443
```

**Comment by blakeembrey** [comment] 2016-01-12 20:50
@maku That's a much better error, thank you! Are you behind a proxy at all? Sounds like it might be related to https://github.com/typings/typings/issues/106, if so.

**Comment by maku** [comment] 2016-01-15 07:49
@blakeembrey Yes, I am behind a proxy.

**Comment by gdi2290** [comment] 2016-03-13 04:21
I'm going to close this issue. If you have anymore typings problems you can also open an issue in https://github.com/typings/typings for problems with typings or more info on proxy

**Closed by gdi2290** 2016-03-13 04:21 UTC
Labels: help wanted
