### ISSUE TITLE
Can't install jointjs typings

### ISSUE THREAD

**Issue by vasyl-romanchak** [AngularClass/angular2-webpack-starter#274] opened 2016-01-29 20:30 UTC
Here is what I did after project setup:

```
npm i jointjs --save
typings install jointjs --save --ambient
```

after that jointjs typings couldn't find out Backbone typings, as I understood typings won't install peer dependencies.

so again
```
typings install jquery --save --ambient
typings install backbone --save --ambient
typings install underscore --save --ambient
```

And still I have a lot of errors:

```
ERROR in /Users/vasylromanchak/ngpapersdev/typings/browser/ambient/jquery/jquery.d.ts
(3205,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.

ERROR in /Users/vasylromanchak/ngpapersdev/typings/browser/ambient/jointjs/jointjs.d.ts
(72,29): error TS2315: Type 'View' is not generic.

ERROR in /Users/vasylromanchak/ngpapersdev/typings/browser/ambient/jointjs/jointjs.d.ts
(89,32): error TS2315: Type 'View' is not generic.

ERROR in /Users/vasylromanchak/ngpapersdev/typings/browser/ambient/backbone/backbone.d.ts
(211,36): error TS1210: Invalid use of 'arguments'. Class definitions are automatically in strict mode.

ERROR in /Users/vasylromanchak/ngpapersdev/src/app/editor/directives/drawing.ts
(2,24): error TS2307: Cannot find module 'jointjs'.

ERROR in /Users/vasylromanchak/ngpapersdev/src/app/editor/editor.spec.ts
(16,20): error TS2307: Cannot find module './home'.
```

Can you guys help me  install jointjs library ontop of your boilerplate...
Also is there anyway to replace underscore with lodash?

**Comment by vasyl-romanchak** [comment] 2016-01-29 20:54
btw as I understood this error
(3205,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.

could be fixed only by splitting project build process onto tests & app stage

**Comment by blakeembrey** [comment] 2016-01-29 21:51
@vasyl-romanchak When you install with the `--ambient` flag, it's just copying the source files. You've just copied https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jointjs/jointjs.d.ts and https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/backbone/backbone.d.ts into your project. For backbone, it looks like you should install https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/backbone/backbone-global.d.ts instead. You can open issues at https://github.com/DefinitelyTyped/DefinitelyTyped/issues to fix these definitions and so you can import the module `jointjs`.

**Comment by vasyl-romanchak** [comment] 2016-01-31 00:08
Thanks for the quick reply!

Unfortunately I wasn't able to import jointjs via;
```
import * as joint from 'jointjs';
//or
import joint = require('jointjs');
```

only simple require('jointjs') was possible, but its not what I wanted to.

So I decided to write my own typings in custom_typings.d.ts

Basically I just copied their joitn definition in my project... and I saw that their module definitions starts with
```
declare module joint {
    module dia {
    ...
    }
}
````

After some googling I changed `declare module joint` to `declare module "jointjs"` in my own declaration. And import warnings are gone. But I still had to reference jointjs peer dependencies manually.
```
ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(12,9): error TS2300: Duplicate identifier 'at'.

ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(16,9): error TS2300: Duplicate identifier 'pushState'.

ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(17,9): error TS2300: Duplicate identifier 'root'.

ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(21,9): error TS2300: Duplicate identifier 'trigger'.

ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(26,9): error TS2300: Duplicate identifier 'routes'.

ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(30,9): error TS2300: Duplicate identifier 'silent'.

ERROR in /Users/vasylromanchak/ng2-papersdev/typings/browser/ambient/backbone-global/backbone-global.d.ts
(34,9): error TS2300: Duplicate identifier 'validate'.

```

I don't understand what I'm doing wrong here... And coming back to their typings. What the difference between:
`declare module joint` vs `declare module "jointjs" { export = joint; module joint { ...`
probably I was able to get out from import errors only because I added export ?

**Comment by blakeembrey** [comment] 2016-02-08 22:32
@vasyl-romanchak Can you share your project or a reproduction? Make sure you're only referencing either the browser or main version from `typings`.

As for the difference, you can read about it from TypeScript. One is declaring a namespace and the other is declaring a module.

**Comment by gdi2290** [comment] 2016-03-13 04:49
I'm going to close this but if you have anymore problems with this starter you can open another issue. If you have problems with typings you can also look in https://github.com/typings/typings for solutions or issues thanks

**Closed by gdi2290** 2016-03-13 04:49 UTC
Labels: [Typings] other module problems
