### ISSUE TITLE
Brand new download and attempt to run fails ...

### ISSUE THREAD

**Issue by ghost** [AngularClass/angular2-webpack-starter#132] opened 2015-11-22 20:40 UTC
I just downloaded, ran all the installs, did my product upgrades, etc (unless I missed a step ...)
When I execute the command "npm run server", it fails to start. Any help would be appreciated. 
I'm running Windows 10, and will be using either VS Code, or VS Community w/ Node.js tools for my IDE. The error below is from running the command(s) in the Powershell command window.

Here's what shows in my Windows 10 Powershell window:
```bash
PS C:\dev\samples> cd ng2webpackstarter
PS C:\dev\samples\ng2webpackstarter> npm install
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
PS C:\dev\samples\ng2webpackstarter> npm run server

> angular2-webpack-starter@0.0.0 server C:\dev\samples\ng2webpackstarter
> webpack-dev-server --inline --colors --display-error-details --display-cached --port 3000

module.js:338
    throw err;
    ^

Error: Cannot find module './dependencies/TemplateArgumentDependency'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\dev\samples\ng2webpackstarter\node_modules\webpack\lib\NormalModule.js:14:34)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@0.0.0 server: `webpack-dev-server --inline --colors --display-error-details --display-cached --port 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@0.0.0 server script 'webpack-dev-server --inline --colors --display-error-details --display-cached --port 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --colors --display-error-details --display-cached --port 3000
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\samples\ng2webpackstarter\npm-debug.log
PS C:\dev\samples\ng2webpackstarter>
```

**Comment by gdi2290** [comment] 2015-11-22 21:23
what version of `node` and `npm` are you running?

**Comment by silverfox1948** [comment] 2015-11-23 04:08
I completely uninstalled node and npm, re-booted, and re-downloaded and re-installed node.

 

It still is failing. Here’s what I currently have:

 

c:\Dev\samples\ng2WebpackStarter>npm -v

2.14.7

 

c:\Dev\samples\ng2WebpackStarter>node -v

v4.2.2

 

 

Regards, 

Steven Archibald, President

Steven Archibald Consulting Corporation

e-mail: steven.archibald@sa-consult.com

Architecture/ Design/ Development

 

"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away." 
 <http://www.brainyquote.com/quotes/quotes/a/antoinedes121910.html> Antoine de Saint-Exupery.

**Comment by dotcs** [comment] 2015-11-23 07:21
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5

I'm not using Windows 10, but I'm quite sure that `fsevents@1.0.5` should not have any problems with Windows 10.

You could try to delete the `node_modules` folder and run `npm install` again to force a rebuild of the complete dependency graph. Let's see if this fixes the problem.

**Comment by johanbove** [comment] 2015-12-04 13:56
@dotcs  Any luck getting it to work? I'm currently struggling with a very similar issue.

**Comment by dotcs** [comment] 2015-12-05 10:12
@johanbove Nope, as said above I don't use Windows 10. I did a fresh `git clone` of the repo and `npm install` on OS X without any issues. The problem must be either Windows 10 specific or some kind of incompatibility between node versions. I think the latter is more likely which is why I recommended to remove the `node_modules` folder in the comment above. Can you explain in detail which steps to took and what exactly the problem is to help us track down the problem? It might help also to post the contents of the `npm-debug.log` file.

**Comment by Plummat** [comment] 2015-12-10 18:31
looks like this is an issue introduced in npm 3.5

**Comment by gdi2290** [comment] 2015-12-21 16:14
@silverfox1948  can you update npm https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by gdi2290** [comment] 2016-01-03 03:06
can you run `npm run clean:install`

**Comment by binarious** [comment] 2016-01-12 14:16
Had the same error on CentOS 7 (node v4.2.1, npm v3.5.4)
`npm run clean:install` fixed it for me. Thanks @gdi2290.

**Comment by gdi2290** [comment] 2016-01-15 06:12
if `npm run clean:install` doesn't work can you open another issue so closing this for now

**Closed by gdi2290** 2016-01-15 06:12 UTC
Labels: help wanted
