### ISSUE TITLE
npm run lint fail on oneLineRule

### ISSUE THREAD

**Issue by lpalli** [AngularClass/angular2-webpack-starter#992] opened 2016-09-13 12:08 UTC
[X] bug report

Running `npm run lint` fail

To reproduce:
1. Clone the repository on the [last commit](https://github.com/AngularClass/angular2-webpack-starter/commit/2f614b45851056c2ec463133267cb7f8c36c994d)
2. Run `npm install`
3. Run `npm run lint`

The problem seems the same as #833

The logs:

$ npm run lint

> angular2-webpack-starter@5.0.5 lint D:\Projects\angular2-webpack-starter
> npm run tslint "src/*_/_.ts"
> 
> angular2-webpack-starter@5.0.5 tslint D:\Projects\angular2-webpack-starter
> tslint "src/*_/_.ts"

D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\rules\oneLineRule.js:163
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\rules\oneLineRule.js:163:17)
    at OneLineWalker.SyntaxWalker.visitNode (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:366:22)
    at D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
    at visitEachNode (D:\Projects\angular2-webpack-starter\node_modules\typescript\lib\typescript.js:7959:30)
    at Object.forEachChild (D:\Projects\angular2-webpack-starter\node_modules\typescript\lib\typescript.js:8117:24)
    at OneLineWalker.SyntaxWalker.walkChildren (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:190:14)
    at OneLineWalker.SyntaxWalker.visitNode (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:414:22)
    at OneLineWalker.SyntaxWalker.walk (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (D:\Projects\angular2-webpack-starter\node_modules\tslint\lib\language\rule\abstractRule.js:19:16)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "tslint" "src/**/*.ts"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 tslint: `tslint "src/**/_.ts"` npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 tslint script 'tslint "src/__/_.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tslint "src/*_/_.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\angular2-webpack-starter\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "lint"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 lint: `npm run tslint "src/**/*.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 lint script 'npm run tslint "src/**/*.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run tslint "src/**/*.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\angular2-webpack-starter\npm-debug.log

luca@lp-hp850 MINGW64 /d/Projects/angular2-webpack-starter (master)

**Comment by lpalli** [comment] 2016-09-14 12:13
If I remove the rule `one-line` the others rules work fine.

**Comment by sihu** [comment] 2016-10-12 09:19
the line causing the problem is [src/custom-typings.d.ts#L47](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/custom-typings.d.ts#L47). If I exclude it, it works, without disabling the rule.

**Comment by xtianus79** [comment] 2016-11-09 21:05
why is this a problem... this thing is way too bloated

**Comment by Andrey-Pavlov** [comment] 2016-11-14 11:39
npm install tslint@next helps me
https://github.com/palantir/tslint/issues/1425

**Comment by michaeljota** [comment] 2016-11-14 12:44
As @Andrey-Pavlov said, it's a bug in TSLint, it had been reported. However, it only will be fixed in 4.0. So you can update using `npm install tslint@next` or remove the rule, cause the 3.x branch won't get the fix for this. 

My recommendation, if you use TypeScript 2.0.x you should upgrade, cause the 4.0 it's being update to this compiler.

**Closed** 2017-01-25 06:40 UTC
