### ISSUE TITLE
Bindings won't refresh in Firefox (presumably caused by core-js/es6/es6-promise)

### ISSUE THREAD

**Issue by borisvasilenko** [AngularClass/angular2-webpack-starter#709] opened 2016-06-18 07:58 UTC
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

Bindings on the page won't refresh after the XHR/fetch completes. 

* **the steps to reproduce** 

Call fetch and try to display something when the loading complete. Please, see an example here:
https://github.com/borisvasilenko/angular2-webpack-starter/commit/eaaf7944d8af28a1e7702f229cceaf3e612dd59c

Browser: Firefox.

* **What is the expected behavior?**

The page should display the text: 'THIS SHOULD BE DISPLAYED'

* **Please tell us about your environment:**

   - Angular version: 2.0.0-rc.1, 2.0.0-rc.2
   - Browser: [Firefox 39.0]

* **Other information** 

We've updated our project to the angular2-webpack-starter with Angular RC1.
What I've found out by trial and error:

In Firefox

1. NgZone.onStable and NgZone.onUnstable do not occur after the XHR/fetch completes. 

2. I've managed to work around this issue by excluding core-js/es6/promise. So, I suggest that this polyfill breaks angular.

You can see my fix here: https://github.com/borisvasilenko/angular2-webpack-starter/commit/da2ac7966279e120dd00f6b22837960225b30329

**Comment by gdi2290** [comment] 2016-06-19 05:54
thanks, fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/c1d8fd5235a427ceecffd39ada5ccba192905afa

**Closed by gdi2290** 2016-06-19 05:54 UTC

**Comment by gdi2290** [comment] 2016-06-21 05:07
cc @zloirock there seems to be a problem with the promise polyfill in firefox or a conflict between `zone.js`, `core-js`, and firefox promise

**Comment by zloirock** [comment] 2016-06-21 07:16
Very strange. Can you write a full reproducible example with all environment?  I'll play with it when I'll have some time.

**Comment by DavideViolante** [comment] 2016-06-22 20:09
@zloirock I experienced this bug too with Chrome and Angular rc.3. If I import 'core-js/es6/promise' the page doesn't load all the bindings. There are no errors in console at all. All others files in core-js/es6 folder can be imported without any issue. To reproduce it easly create a very basic project using webpack (you can clone my MEAN stack project) and into vendor.ts try to write "import 'core-js/es6';" or all the files individually, including promise.

**Comment by commfort** [comment] 2016-07-18 08:35
@borisvasilenko learn some angular before start coding.  
If you need data from server best approach to use Http service from '@angular/http'. Because it has required change detection code.

But if you really need to use async code that located outside of angular app, you need to wrap it with [NgZone.run(yourCode)](https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html#!#run-anchor) or finalize it with [ChangeDetectorRef.detectChanges()](https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html#!#detectChanges-anchor)

http://stackoverflow.com/questions/34827334/triggering-angular2-change-detection-manually

http://stackoverflow.com/questions/32768854/using-promises-and-zones-in-angular2


Everything worked perfectly for me with import 'core-js/es6'; and now I have a bug and need manually change polyfills.ts to previous version

**Comment by borisvasilenko** [comment] 2016-07-18 10:12
@commfort 

Thanks, i know about NgZone.run and detectChanges.
but, 
http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
"Angular [2] allows us to use native APIs directly." 
So I believe, that you're not right, and that the NgZone.run or detectChanges are unnecessary.

I also believe, that your work-around is worse than removing the 'core-js/es6' import, because it pollutes the project code with unnecessary calls like NgZone.run or detectChanges. 

And yes, I know about @angular/http, but issue is not about @angular/http. I still need to use raw fetch API at some places. And I need to use it directly, without NgZone.run or other work-arounds.

**Comment by linweiwei123** [comment] 2016-11-23 06:45
Is this issue solved? How to use es6-promise if do not import it?

**Comment by gdi2290** [comment] 2016-11-23 10:34
I think zone.js provides it's own promise polyfill so manually removing `core-js`'s is what I've been doing
