### ISSUE TITLE
Error angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:22:27 Module 'webdriver' has no exported member 'IButton'.

### ISSUE THREAD

**Issue by Renaud009** [AngularClass/angular2-webpack-starter#1038] opened 2016-09-21 23:22 UTC
####I'm submitting a bug report concerning a fresh install of current the master branch.
Current Node v.6.2.0
Current npm v.3.8.9

####Steps to reproduce:
- $ git clone master branch
- $ npm install
- $ npm install webpack@2.1.0-beta.22 --save #https://github.com/AngularClass/angular2-webpack-starter/pull/1018
- $ npm start

#### Error Stackwebpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:22:27 
    Module 'webdriver' has no exported member 'IButton'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:25:24 
    Module 'webdriver' has no exported member 'IKey'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:28:45 
    Property 'Error' does not exist on type 'typeof error'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:29:40 
    Module 'webdriver.error' has no exported member 'IErrorCode'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:36:37 
    Module 'webdriver.logging' has no exported member 'IType'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:37:38 
    Module 'webdriver.logging' has no exported member 'ILevelValues'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:39:67 
    Module 'webdriver.logging' has no exported member 'ILevel'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:40:67 
    Module 'webdriver.logging' has no exported member 'ILevel'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:287:39 
    Property 'stacktrace' does not exist on type 'typeof webdriver'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:288:42 
    Property 'stacktrace' does not exist on type 'typeof webdriver'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:303:35 
    Module 'webdriver' has no exported member 'stacktrace'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:340:55 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:414:52 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:462:53 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:664:29 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:673:32 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:704:39 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:725:35 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:801:48 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:808:30 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1111:32 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1139:30 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1362:51 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1363:42 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1364:41 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1440:55 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1461:60 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1477:41 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1491:51 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1505:58 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1574:79 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1594:55 
    Module 'webdriver' has no exported member 'Locator'.
[default] /home/osboxes/Downloads/angular2-webpack-starter/node_modules/@types/protractor/index.d.ts:1614:36 
    Module 'webdriver' has no exported member 'Locator'.
[default] Checking finished with 33 errors

Any ideas what's wrong?

**Comment by sanex3339** [comment] 2016-09-22 05:26
same

**Comment by Mandersen21** [comment] 2016-09-22 07:52
same

**Comment by bonaventoora** [comment] 2016-09-22 08:23
Duplicate of #1031, hotfix there.

**Closed** 2016-09-22 11:38 UTC
